name = "AmbientForcing"
uuid = "e2f64fc7-2bff-4a84-bd3f-8a41fe73f145"
authors = ["Anna and contributors"]
version = "0.1.0"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
NetworkDynamics = "22e9dc34-2a0d-11e9-0de0-8588d035468b"
PowerDynamics = "cc46b21f-1b17-51c2-b642-af74c3d3a8be"

[compat]
PowerDynamics = "2.4"
NetworkDynamics = "0.5"

julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
