name = "AmbientForcing"
uuid = "e2f64fc7-2bff-4a84-bd3f-8a41fe73f145"
authors = ["Anna and contributors"]
version = "0.1.0"

[deps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"

[compat]
DifferentialEquations = "6.16"
NetworkDynamics = "0.4"
PowerDynamics = "2.4"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
